# This file was generated by GoReleaser. DO NOT EDIT.
cask "gumlet" do
  name "gumlet"
  desc "Gumlet CLI – manage video and image assets from the command line"
  homepage "https://www.gumlet.com"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gumlet"

  on_macos do
    on_intel do
      url "https://github.com/gumlet/cli/releases/download/v#{version}/gumlet_darwin_x86_64.tar.gz"
      sha256 "36c1b41b0d36f33ca4c3778288f8c36ff6ea78ee74c522fab9ace75e2f21b019"
    end
    on_arm do
      url "https://github.com/gumlet/cli/releases/download/v#{version}/gumlet_darwin_arm64.tar.gz"
      sha256 "a2c997f1418aaca0f0dd7e70a9c744aa28c19eb5d97eb2fbbfd2e366a6ff69e4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gumlet/cli/releases/download/v#{version}/gumlet_linux_x86_64.tar.gz"
      sha256 "eea2a7144e41b89c3939c431a54ed9abe1410e4fb7f34ba2bb3ff3629655c6ab"
    end
    on_arm do
      url "https://github.com/gumlet/cli/releases/download/v#{version}/gumlet_linux_arm64.tar.gz"
      sha256 "f2415376f92cfe8f40e0b5b79271bcc122e9b912000c27ab7d7a5b5a33364c71"
    end
  end

  # No zap stanza required
end
